import type { Metadata } from "next";
import { PT_Serif, Spline_Sans_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "../components/providers";
import { SyncConfigWithLocalStorage } from "./_components/config-dialog/sync-config";
import { Header } from "./_components/header/header";
import "./globals.css";

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  weight: ["400", "700"],
  subsets: ["latin"],
  style: "normal",
});

const splineSansMono = Spline_Sans_Mono({
  variable: "--font-spline-sans-mono",
  weight: ["300", "700"],
  subsets: ["latin"],
  style: "normal",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${ptSerif.variable} ${splineSansMono.variable} font-geist-sans font-medium ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <SyncConfigWithLocalStorage />
        </Providers>
      </body>
    </html>
  );
}
