import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "../components/providers";
import { ConfigDialog } from "./_components/config-dialog/config-dialog";
import { SyncConfigWithLocalStorage } from "./_components/config-dialog/sync-config";
import "./globals.css";

const helveticaNeueLtStd = localFont({
  src: "./fonts/HelveticaNeueLTStd.otf",
  variable: "--font-helvetica-neue-lt-std",
  weight: "100 900",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${helveticaNeueLtStd.variable} font-geist-sans font-medium ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <ConfigDialog />
          <SyncConfigWithLocalStorage />
        </Providers>
      </body>
    </html>
  );
}
